root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/server ./cmd/balance"

# Local onde estará o executável do build (binário).
bin = "./tmp/server"

exclude_dir = ["tmp"]

exclude_regex = ["_test\\.go"]

exclude_unchanged = true

include_ext = ["go", "tpl", "tmpl", "html"]

log = "build-errors.log"

stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

main_only = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false 