FROM golang:1.22

WORKDIR /app/

RUN apt-get update && apt-get install -y librdkafka-dev

RUN apt-get install git
RUN git clone https://github.com/devfullcycle/fc-eda.git .

RUN go mod tidy
EXPOSE 8080

CMD [ "go", "run", "cmd/walletcore/main.go" ]